version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.10.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: npm install
      - run: npm test
