version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.10.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - run:
          name: Run tests
          command: npm test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run build
      - run: npx yo ./generators/app/index.js test/data/fixtures.xml --dryRun

      - persist_to_workspace:
          root: ~/repo
          paths: [.]

#  deploy:
#    steps:
#      - attach_workspace:
#          at: ~/repo
#      - run:
#          name: Authenticate with registry
#          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
#      - run:
#          name: Publish package
#          command: npm publish
