name: 'build-test'
on: # rebuild any PRs and main branch changes
    pull_request:
    push:
        branches:
            - master
            - 'releases/*'

jobs:
    build:
        name: Build and test
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-node@v2
                with:
                    node-version: 16

            -   uses: actions/setup-python@v4
                with:
                    python-version: '3.10'

            -   run: node -v
            -   run: npm -v
            -   run: python --version

            -   name: Cache node modules
                id: cache-npm
                uses: actions/cache@v2
                with:
                    # npm cache files are stored in `~/.npm` on Linux/macOS
                    path: |
                        ~/.npm
                        **/node_modules

                    key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-build-

            -   if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
                name: List the state of node modules
                continue-on-error: true
                run: npm list

            -   run: npm install
            -   run: npx nx connect-to-nx-cloud
            -   run: npm run compile
            -   run: npm link
            -   run: npm run generate
            -   run: npm run dockerBuild
            -   run: npm test
